### ISSUE TITLE
Have a page that describes each component in VS Code

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-docs#1842] opened 2018-09-10 21:39 UTC
See https://github.com/Microsoft/vscode/issues/58226#issuecomment-419678487. Although this came in as a feedback for extensibility, I think it would help with regular users too.

The page should breakdown VS Code's UI and explain the terms we use for different parts of VS Code.

**Comment by octref** [comment] 2018-09-12 17:56
We already have this page, but it does not go deep enough:

https://code.visualstudio.com/docs/getstarted/userinterface

We should have some more illustration as the top picture:

![image](https://user-images.githubusercontent.com/4033249/45443716-6285c780-b67a-11e8-813e-79300a213c43.png)

For the 5 views that we have and all the panels that we have.

**Comment by nealot** [comment] 2018-09-12 20:40
I think the problem is with how the current information is presented; headers need to be organized based on context. Why does the "Working with Tabs" header come 4 sections after "Tabs"? Also, the "Indent Guides" is a child header of "Minimap - outline view" -- this doesn't make any sense.  Not to mention that with the recent addition of the actual outline view, this label can be misleading.

There's a lot of noise on that page and I think it would benefit from someone putting all the information together in logical hierarchial structure. 

> For the 5 views that we have and all the panels that we have.

![image](https://user-images.githubusercontent.com/36805289/45451678-beb41000-b6a9-11e8-9aec-133c3b6c6b1c.png)

So are all panels views? Or are panels separate from views? Because "View: Open view" displays the image above.

**Comment by gregvanl** [comment] 2020-03-23 15:56
Current User Interface page is performing well 85% CSAT. Creating a page for each UI component would be costly to create and maintain (as UI changes). Closing.

**Closed by gregvanl** 2020-03-23 15:56 UTC
Labels: doc-enhancement, extensibility
