### ISSUE TITLE
Need to document work space recommended extensions

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#618] opened 2016-09-30 13:19 UTC
We have a forward link in the product that needs to point to valid documentation and then we need to update the fwlink

![image](https://cloud.githubusercontent.com/assets/172399/18992953/4b05150a-8721-11e6-9ffd-46b1bc0e562a.png)

**Comment by gregvanl** [comment] 2016-09-30 17:35
I believe this is a duplicate of https://github.com/Microsoft/vscode-docs/issues/614.
What is odd is that the LinkId in the snapshot doesn't match, I think it should be 827846. 
733558 points to the tasks topic.

**Closed by gregvanl** 2016-09-30 17:35 UTC
Labels: important

**Comment by gregvanl** [comment] 2016-09-30 17:36
Looks like the fwlink in https://github.com/Microsoft/vscode/blob/master/.vscode/extensions.json is stale
