### ISSUE TITLE
404 Error cannot download

### ISSUE THREAD

**Issue by muhohokenya** [microsoft/vscode-docs#6509] opened 2023-07-18 21:21 UTC

**Comment by Loaded-Dice** [comment] 2023-07-18 21:26
Can confirm - Win 10 Download gets redirected to:
https://code.visualstudio.com/sha/undefined

**Comment by azeek21** [comment] 2023-07-18 21:28
Any download link will forward to https://code.visualstudio.com/sha/undefined 

Also I saw at https://code.visualstudio.com/sha the api response property `sha256hash` is `Not Provided`. For any `platform/build/os`.

**Comment by Loaded-Dice** [comment] 2023-07-18 21:32
This is one of the incorrect hashed query strings:  https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user

**Comment by gregvanl** [comment] 2023-07-18 21:38
As a workaround, you can create the download URL by following the platform-specific URL patterns documented in https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

For example: https://update.code.visualstudio.com/1.80.1/win32-x64/stable

**Comment by Loaded-Dice** [comment] 2023-07-18 21:38
Direct download link mentioned here:
> https://github.com/microsoft/vscode-docs/issues/6507#issuecomment-1640988979

https://az764295.vo.msecnd.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/VSCodeUserSetup-x64-1.80.1.exe

and here:
> https://github.com/microsoft/vscode-docs/issues/6507#issuecomment-1641028224

https://update.code.visualstudio.com/1.80.1/win32-x64/stable

**Comment by Tunji-og** [comment] 2023-07-18 22:07
what about one for mac os

**Comment by rzhao271** [comment] 2023-07-18 22:26
Duplicate of https://github.com/microsoft/vscode-docs/issues/6496

**Closed by rzhao271** 2023-07-18 22:26 UTC
