### ISSUE TITLE
virtual environment not activated in terminal with anaconda-project

### ISSUE THREAD

**Issue by acalvino4** [Microsoft/vscode-docs#2435] opened 2019-02-25 17:30 UTC
I am using anaconda-project to manage my environments.  I've used 'Python: Select Interpreter' in the VSCode command palette to select the interpreter for the project, and it is recognized in the bottom left of the screen.  However, when I open an integrated terminal, it seems that vscode attempts to activate the environment but fails to find it.  Here is the error message:
```
$ activate default
Could not find conda environment: default
You can list all discoverable environments with the `conda info --envs`.
```
Following the suggestion, I get:
```
$ conda info --envs
# conda environments:
#
base                  *  C:\ProgramData\Anaconda3
                         C:\Users\acalv\CodeProjects\DataScience\BruteForceLinearRegression\envs\default
                         C:\Users\acalv\CodeProjects\DataScience\MarkovChain\envs\default
```
The environment I want is the last one, so conda knows about it.  And again, VS Code does recognize the interpreter associated with this environment:
` WorkspaceSettings.Python.PythonPath = C:\Users\acalv\CodeProjects\DataScience\MarkovChain\envs\default\python.exe`

**Comment by acalvino4** [comment] 2019-02-25 18:00
Update: I just noticed that `WorkspaceSettings.Python.CondaPath` is blank.  Could that be the cause of the issue?

**Comment by kraigb** [comment] 2019-02-25 18:47
@acalvino4 This looks like a bug in the extension (rather than the documentation). In that case, please check on https://github.com/Microsoft/vscode-python/issues if the issue is already filed; if not, do file this issue there. In the meantime, I'm closing this one (as this repo is docs issues only). Thanks.

**Closed by kraigb** 2019-02-25 18:47 UTC
Labels: python

**Comment by acalvino4** [comment] 2019-02-25 19:56
I see.  I posted here, because I was directed to by this page: https://code.visualstudio.com/docs/python/environments#_environments-and-terminal-windows

**Comment by kraigb** [comment] 2019-02-25 22:01
Yes, I have the link to the doc issues first so I can filter what goes to the product backlog. That way I can send folks to the engineering team only when necessary, as in your case. Thanks for understanding. :)
