### ISSUE TITLE
A11y_Visual Studio Code_Docs Setup_Keyboard: After selecting any link form left navigation site map, keyboard focus goes to the start of the page instead of revealed content

### ISSUE THREAD

**Issue by NiharikaTipirishetty** [microsoft/vscode-docs#4529] opened 2021-05-06 06:40 UTC
[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

GitHubTags:#A11y_Visual Studio Code##A11yAuto#TabStops#A11ySev2#A11yTCS#A11yMAS#Chrome#DesktopWeb#Win10#Visual Studio Code Services#WCAG2.4.3#Focus Order#Benchmark-VisualStudioCode-Web-Apr2021

### Environment details:
Application Name: Visual Studio Code
URL:[Visual Studio Code](https://code.visualstudio.com/docs/setup/linux)
Windows Version: Version 20H2 (OS Build 19042.928)
Browser: Chrome Version 90.0.4430.85 (Official Build) (64-bit)

### Repro Steps:

1. Hit [Visual Studio Code](https://code.visualstudio.com/docs/setup/linux) link
2. Tab till Docs link in top navigation section and press enter
3. Tab till Set up in left navigation pane and select Linux/Mac OS
4. Verify that after selecting Linux, keyboard focus goes to the start of the page instead of revealed content.

### Actual Result:
After selecting any link form left navigation site map, keyboard focus goes to the start of the page instead of revealed content

### Expected Result:
After selecting any link form left navigation site map, keyboard focus should go to the revealed content i.e., whichever link is selected.

### User Impact:
Keyboard users will find it difficult to navigate all the controls and then enter into the page.

### Attachment:

https://user-images.githubusercontent.com/83570638/117252707-f4622480-ae63-11eb-9ae3-6edcd73f8ccf.mp4

**Comment by rzhao271** [comment] 2021-07-08 19:55
Marking this task as a duplicate of https://github.com/microsoft/vscode-docs/issues/4524, because [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/winprog/disabling-strict) uses the "Skip to main content" approach to resolve this issue.

**Closed by rzhao271** 2021-07-08 19:55 UTC
Labels: accessibility, docs-experience, duplicate

**Comment by kupatkar99** [comment] 2023-02-13 05:58
Issue is fixed. 
[4529_Fixed.webm](https://user-images.githubusercontent.com/98530069/218381962-2fb4cd9d-9ed4-4a94-bafe-0edbd3b61cb0.webm)
#Closed;
