### ISSUE TITLE
docs: missing documentation on `activationEvents`

### ISSUE THREAD

**Issue by vince-fugnitto** [microsoft/vscode-docs#6039] opened 2023-02-09 19:11 UTC
**Description**

The [activation events](https://code.visualstudio.com/api/references/activation-events) documentation is missing a number of available `activationEvents` which should be listed for clarity as the docs state "Here is a list of all available Activation Events".

A couple of missing events are as follows:
- `onTaskType`
- `onNotebook`
- `onWalkthrough`
- `onOpenExternalUri`
- `onEditSession`
- ...

The information is at least available in the schema.

**Comment by gregvanl** [comment] 2023-02-27 05:00
Hi @vince-fugnitto Thanks for pointing this out and entering an issue.
Closing this issue as a duplicate of https://github.com/microsoft/vscode-docs/issues/5745, which calls out the same activation events mentioned here.

**Closed by gregvanl** 2023-02-27 05:00 UTC
Labels: extensibility, doc-bug
