### ISSUE TITLE
Documentation: "Clang on macOS" cannot be reproduced

### ISSUE THREAD

**Issue by Leo-Maxwell** [microsoft/vscode-docs#5701] opened 2022-10-11 05:20 UTC
https://code.visualstudio.com/docs/cpp/config-clang-mac
In the documentation above, the author used Windows VSCode with clang instead of macOS VScode with clang.
I cannot reproduce the steps on my M1 Max Macbook Pro, could you please rewrite that tutorial?

**Comment by DaveSprague** [comment] 2022-11-18 09:41
I also see issues with the documentation page.  There are two issues:

1) the line:
 `".          -std=c++17",
`
is not in the created tasks.json file and as a result, the program fails with an error of:
`
	expected ';' at end of declaration",
	range-based for loop is a C++11 extension [-Wc++11-extensions]
`

2) The cout output of the program appears only in the debug window, not in the Terminal windows.

**Comment by gregvanl** [comment] 2023-04-28 18:33
Resolving at duplicate of more recent https://github.com/microsoft/vscode-docs/issues/6221

**Closed by gregvanl** 2023-04-28 18:33 UTC
Labels: C++, doc-bug

**Comment by AlexandraKemperMS** [comment] 2023-12-19 17:43
Hi @DaveSprague, thank you for pointing this out. With https://github.com/microsoft/vscode-docs/pull/6915 the mac configuration docs have been fixed and updated. If you still see the same issues, please let me know.
