### ISSUE TITLE
Search: update screenshots and mention "Replace across Files"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#394] opened 2016-07-04 12:29 UTC
Refs: https://code.visualstudio.com/docs/editor/codebasics#_search-across-files

With June you can replace across files. As such we should update this section.

**Comment by gregvanl** [comment] 2016-07-11 14:03
Missed this duplicate of https://github.com/Microsoft/vscode-docs/issues/379 during earlier triage.

**Closed by gregvanl** 2016-07-11 14:03 UTC
