### ISSUE TITLE
Callout Extension Manifest Editor extension

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#609] opened 2016-09-27 00:33 UTC
This is a very helpful extension for creating an extension. Worth calling out in our docs somewhere. 

https://marketplace.visualstudio.com/items?itemName=ms-devlabs.extension-manifest-editor

**Comment by gregvanl** [comment] 2016-09-28 19:26
Duplicate of https://github.com/Microsoft/vscode-docs/issues/497 which I'll add to October milestone

**Closed by gregvanl** 2016-09-28 19:26 UTC
