### ISSUE TITLE
Broken link in the JavaScript section

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#985] opened 2017-05-05 18:05 UTC
![image](https://cloud.githubusercontent.com/assets/172399/25758257/16750504-31ce-11e7-80c3-c102c005b17d.png)

// CC @waderyan

**Comment by martiuslim** [comment] 2017-05-14 09:55
Hi, may I check if it's better to relink this to the Intellisense documentation under Visual Studio Code (found here https://code.visualstudio.com/docs/editor/intellisense) or the JavaScript IntelliSense documentation under Visual Studio (found here https://docs.microsoft.com/en-us/visualstudio/ide/javascript-intellisense)?

**Comment by gregvanl** [comment] 2017-05-15 18:38
Hi @martiuslim, I think the issue is that the TypeScript language service (codebase Salsa) wiki page https://github.com/Microsoft/TypeScript/wiki/Salsa is no longer available. We need to find a new language service topic on the TypeScript site. We don't want to link back to our own site.

**Comment by martiuslim** [comment] 2017-05-16 02:33
Hi @gregvanl, would this be better then? https://github.com/Microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio

**Comment by gregvanl** [comment] 2017-05-16 04:47
@martiuslim I think you're right. You are the third person to point me to that topic today and I believe most of the earlier Salsa page content moved here. I think we can use it even if it assume the user is coming from regular Visual Studio (2015 or 2017).

**Comment by gregvanl** [comment] 2017-05-16 17:29
Fixed with https://github.com/Microsoft/vscode-docs/pull/1001

**Closed by gregvanl** 2017-05-16 17:29 UTC
