### ISSUE TITLE
Documentation about how extensions can persist secrets is outdated

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-docs#4955] opened 2021-11-11 17:21 UTC
It still states that VS Code does not provide a secret persistence mechanism. Ever since [`ExtensionContext#secrets`](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext) arrived this is no longer true.

https://github.com/microsoft/vscode-docs/blob/cf997eb179d186fe3b6cf553e1e0d0f612e7b9c9/api/advanced-topics/remote-extensions.md?plain=1#L211-L244

**Comment by pugg11** [comment] 2021-12-23 03:49
Need to access billing.. hacks,dawgz.com

**Comment by pugg11** [comment] 2021-12-23 03:49
https://github.hackoppo.phone.cph.122232468.

**Comment by pugg11** [comment] 2021-12-23 03:50
`[$ curl -i https://api.github.com/users/defunkt  > HTTP/2 200 > etag: W/"61e964bf6efa3bc3f9e8549e56d4db6e0911d8fa20fcd8ab9d88f13d513f26f0]($ curl -i https://api.github.com/users/defunkt  > HTTP/2 200 > etag: W/"61e964bf6efa3bc3f9e8549e56d4db6e0911d8fa20fcd8ab9d88f13d513f26f0) `

**Comment by pugg11** [comment] 2021-12-23 03:50
@nico Weber.con

**Comment by pugg11** [comment] 2021-12-23 03:51
1. 

- [ ] _****
Duplicate of  ##
![hq720](https://user-images.githubusercontent.com/96555888/147185441-f4d2993d-d5fd-4bf1-8d67-c018891bfb35.jpg)
_

**Comment by pugg11** [comment] 2021-12-23 03:51
- #
https://github.hackoppo.phone.cph.122232468.__

**Comment by pugg11** [comment] 2021-12-23 03:51
> `[https://api.github.com/users/defunkt]($ curl -i https://api.github.com/users/defunkt  > HTTP/2 200 > etag: W/"61e964bf6efa3bc3f9e8549e56d4db6e0911d8fa20fcd8ab9d88f13d513f26f0) `

**Comment by pugg11** [comment] 2021-12-23 03:51
> > `[https://api.github.com/users/defunkt]($ curl -i https://api.github.com/users/defunkt  > HTTP/2 200 > etag: W/"61e964bf6efa3bc3f9e8549e56d4db6e0911d8fa20fcd8ab9d88f13d513f26f0) `

**Comment by pugg11** [comment] 2021-12-23 03:52
### `@****`

**Comment by gregvanl** [comment] 2023-10-11 03:13
Updated with https://github.com/microsoft/vscode-docs/pull/6423

**Closed by gregvanl** 2023-10-11 03:13 UTC
Labels: extensibility, doc-bug
