### ISSUE TITLE
VSCode API reference

### ISSUE THREAD

**Issue by rwnkl** [microsoft/vscode-docs#3617] opened 2020-04-27 18:22 UTC
- VSCode Version: 1.44.2
- OS Version: Windows 10 prof 64

Steps to Reproduce:

1. VS Code API Reference links

Does this issue occur when all extensions are disabled?: Yes
All links within the VSCode API reference no longer jump to the exact position.

**Comment by gregvanl** [comment] 2020-04-27 19:37
Related to https://github.com/microsoft/vscode-docs/issues/3416.
Once this is fixed, the link should be displayed.

**Comment by gregvanl** [comment] 2020-04-27 21:43
Hi @rwnkl Can you check if this is a duplicate of #3416? I reverted a change which had broken h2 and h3 link jumps but #3416 is still an issue. Thanks

**Comment by rwnkl** [comment] 2020-04-28 12:00
Hi Greg,
the navigation to the top-level fragments (namespaces, classes, interfaces etc. ) works again exact. The deeper fragments such as for variables, functions, methods etc. still has the issue of inaccurate positioning 
My issue is a duplicate of #3416- sorry.

**Comment by gregvanl** [comment] 2020-04-28 13:53
@rwnkl Thanks for checking. We're working on the best fix for #3416 and appreciate you noticing that we "broke some eggs" along the way.

**Closed by gregvanl** 2020-04-28 13:53 UTC
Labels: API documentation, doc-experience, extensibility
