### ISSUE TITLE
"Debugging Java" provides misleading instructions or debugger doesn't work as intended

### ISSUE THREAD

**Issue by adityasrini** [Microsoft/vscode-docs#1316] opened 2017-12-21 18:49 UTC
In the instructions for using the "[Debugger for Java](https://code.visualstudio.com/docs/java/java-debugging)", the second gif of the instructions and in the "Use" section mention that "If there's no debug configuration file launch.json in your project, the debugger will automatically find the main class and generate the configuration for you to launch your application." This is either false or a bug within the debugger as I've tried doing this with simple "Hello World!" main classes and have not had the debugger automatically detect the main class or give me the option to choose the class as is shown in the [gif](https://github.com/Microsoft/vscode-docs/blob/master/docs/java/images/java-debugging/resolve-main.gif). It may be a better idea to omit this instruction until such a feature is implemented.

VS Code version: 1.18.1
Debugger for Java version: 0.4.0
Language support for Java ™ for Visual Studio Code version: 0.16.0
Installed through Java Extension Pack: 0.2.0
Java --version: 9 build 181
macOS: 10.13.2

**Comment by gregvanl** [comment] 2017-12-28 23:43
Hi @adityasrini, I tried this with a very simple Java application (see below) and the Debugger for Java extension correctly found main class and generated a working launch.json configuration.

```java
package javaapplication1;

public class JavaApplication1 {
    public static void main(String[] args) {
        System.out.println("Greetings!");       
    }
}
```
What might be different with your Hello World! example?
Adding @hexiaokai

**Comment by adityasrini** [comment] 2017-12-29 22:29
My code is the EXACT same as yours! It still does not autodetect. I've previously tried this on code that had lists that were properly imported. This is my launch.json file (added `.txt` to make it upload-able). It only works when I manually specify `"mainClass": "javaapplication1.JavaApplication1"` as one of the properties. 


[launch.json.txt](https://github.com/Microsoft/vscode-docs/files/1593968/launch.json.txt)

**Comment by gregvanl** [comment] 2018-01-12 18:39
@adityasrini I tried to reproduce your issue but wasn't able to. I'm closing this issue since it isn't really a VS Code documentation issue.
If you are still having problems debugging Java with the Debugger for Java extension, you can file an issue in the extensions GitHub repo https://github.com/Microsoft/vscode-java-debug/issues.
Your issue might be a duplicate of https://github.com/Microsoft/vscode-java-debug/issues/191. You can vote that issue up or perhaps provide a Java project in a repo to show the issue.

**Closed by gregvanl** 2018-01-12 18:39 UTC

**Comment by andxu** [comment] 2018-03-05 02:24
@adityasrini I think you have different understanding of the phase with us "If there's no debug configuration file launch.json in your project",  here if you have no launch.json in the .vscode file, we will generate one launch.json for you, if you have any modifications over the launch.json file, our plugin will not generate it for you because we think you as advanced user and have knowledge  of parameters in launch.json, if you delete the mainClass, the plugin will ask you every time providing a list of run-able classes and do no modification to your launch.json

**Comment by robert1ishere** [comment] 2018-03-05 02:54
Yeah I'm not nearly as advanced I'm trying to learn why what you guys are
saying and figure out stuff, on my own it's not a lot of fun especially
when I don't have administrative rights over my phone have no idea how they
even get it but I'm trying,.. I enclose the screenshot I'm still trying to
figure out how to get this accomplished

**Comment by andxu** [comment] 2018-03-05 05:54
So could you please try it again deleting launch.json and F5 and choose 'java' to see whether launch.json is well created and F5 again to see whether you can start debugging.
