### ISSUE TITLE
The terminal process terminated with exit code: 259

### ISSUE THREAD

**Issue by Arslanthought** [microsoft/vscode-docs#3578] opened 2020-04-18 19:30 UTC

**Comment by Arslanthought** [comment] 2020-04-18 19:31
![WhatsApp Image 2020-04-16 at 1 14 43 AM](https://user-images.githubusercontent.com/63039060/79669465-17785280-81d5-11ea-8344-51061854c803.jpeg)

**Comment by gregvanl** [comment] 2020-04-18 20:26
This looks like a duplicate of https://github.com/microsoft/vscode/issues/93455 which is a duplicate of https://github.com/microsoft/vscode/issues/45693.
In general, issues with the VS Code product can be entered at https://github.com/microsoft/vscode/issues. This repo is for VS Code documentation.

**Closed by gregvanl** 2020-04-18 20:26 UTC
