### ISSUE TITLE
Documentation on commands/actions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-docs#1328] opened 2018-01-02 19:54 UTC
_From @tuckermiller on January 2, 2018 16:50_

Is there a comprehensive list of commands/actions in the VS Code documentation? If so, I think it should be more clearly linked to from the keybindings page and if not (I couldn't find it personally) there should be. For example, from the keybindings page:

"You can invoke a command with arguments. This is useful if you often perform the same operation on a specific file or folder. You can add a custom keyboard shortcut to do exactly what you want.

...

The type command will receive {"text": "Hello World"} as its first argument and add "Hello World" to the file instead of producing the default command."

^ That's very useful information to know, but unless you put it there as an example how would I even find out about the type command? How am I supposed to know what commands take arguments? Etc etc. From the same page:

"Below are the some of the possible when clause contexts which evaluate to Boolean true/false:

...

The list above isn't exhaustive"

Where is the exhaustive list? It would really be useful if this was available, anywhere, for people to read.

_Copied from original issue: Microsoft/vscode#41038_

**Comment by tuckermiller** [comment] 2018-01-02 20:11
(apologies for posting in the incorrect location, and this is a dupe of #683... but IMO that issue was closed incorrectly particularly with regards to not listing arguments for commands and this issue's point about when clause contexts)

**Comment by usernamehw** [comment] 2018-02-01 18:27
@gregvanl, could you please reference or copy some of the commands that take arguments:

from : https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands#_commands
to: https://code.visualstudio.com/docs/getstarted/keybindings#_command-arguments

**Comment by gregvanl** [comment] 2021-03-19 16:27
Closing at covered by other issues with `commands` label asking about commands that take arguments https://github.com/microsoft/vscode-docs/issues/4298 and commands that are called with arguments  https://github.com/microsoft/vscode-docs/issues/2409

**Closed by gregvanl** 2021-03-19 16:27 UTC
Labels: commands, doc-enhancement
