### ISSUE TITLE
A section does not get selected

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/vscode-docs#4204] opened 2020-12-29 11:19 UTC
In [this page](https://code.visualstudio.com/api/extension-guides/debugger-extension) there is a link in the right menu, "Anatomy of the package.json of a Debugger Extension", that doesn't get lit once clicked. It correctly sends you to the section it links to, but it doesn't lit. Instead, the one that gets lit is the previous one, "Development Setup for Mock Debug".

**Comment by adithyasunil26** [comment] 2021-01-01 18:12
As far as I understand this is an issue with the webpage javascript. Can someone please direct me to the location of the webpage source ?

**Comment by gregvanl** [comment] 2021-01-03 18:08
Hi @adithyasunil26 Thank you for your offer to help fix the issue. The VS Code website repository is not public and we don't accept submissions. 
The issue is likely due to the period in "package.json". While it is indeed a bug and does look odd, it doesn't affect user navigation of the topic so closing.

**Closed by gregvanl** 2021-01-03 18:08 UTC
Labels: doc-experience

**Comment by adithyasunil26** [comment] 2021-01-03 18:18
Yes, that makes sense. 
Okay 👍🏻
