### ISSUE TITLE
user_setting for HTML

### ISSUE THREAD

**Issue by tangxiaolang101** [Microsoft/vscode-docs#288] opened 2016-04-26 03:31 UTC
I want to type some JavaScript code in a file of HTML.For example:
`<script>
var a = document.....
</script>`
How to set the suggested elements.
Use the "files.associations"?
Please help me.

**Comment by egamma** [comment] 2016-04-26 07:09
This is currently not supported by the JavaScript language service, sorry.

Closing as a duplicate of https://github.com/Microsoft/vscode/issues/3995

**Closed by egamma** 2016-04-26 07:09 UTC
