### ISSUE TITLE
why cand i install vs code

### ISSUE THREAD

**Issue by Phantomthesigma** [microsoft/vscode-docs#6504] opened 2023-07-18 19:39 UTC
```[tasklist]
### Tasks
```

**Comment by gregvanl** [comment] 2023-07-18 21:36
As a workaround, you can create the download URL by following the platform-specific URL patterns documented in https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

For example: https://update.code.visualstudio.com/1.80.1/win32-x64/stable

**Comment by rzhao271** [comment] 2023-07-18 22:27
Duplicate of https://github.com/microsoft/vscode-docs/issues/6496

**Closed by rzhao271** 2023-07-18 22:27 UTC
