### ISSUE TITLE
Attempting to download VSCode from website results in 404

### ISSUE THREAD

**Issue by lanierhall** [microsoft/vscode-docs#6507] opened 2023-07-18 20:53 UTC

**Comment by Tigereyes-shine** [comment] 2023-07-18 20:58
Same issue here

**Comment by Manuellama** [comment] 2023-07-18 21:03
It seems the sha string is undefined when trying to get the download from the Visual Studio Code webpage.
I managed to download latest Windows version using this url:
https://az764295.vo.msecnd.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/VSCodeSetup-x64-1.80.1.exe
from the visual studio webpage here:
https://[update.code.visualstudio.com/api/versions/1.80.1/win32-x64/stable](https://update.code.visualstudio.com/api/versions/1.80.1/win32-x64/stable)

Using this answer from Stackoverflow:
https://stackoverflow.com/questions/67287095/get-sha256-hash-for-visual-studio-code-installer-file-programmatically

**Comment by whitehotaru** [comment] 2023-07-18 21:03
Same here when trying to download the mac build.

**Comment by Manuellama** [comment] 2023-07-18 21:07
https://code.visualstudio.com/updates/v1_80

Here, downloads seems to work.

**Comment by whitehotaru** [comment] 2023-07-18 21:11
@Manuellama It does, thanks. I just found the same link.

**Comment by gregvanl** [comment] 2023-07-18 21:37
As a workaround, you can create the download URL by following the platform-specific URL patterns documented in https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

For example: https://update.code.visualstudio.com/1.80.1/win32-x64/stable

**Comment by rzhao271** [comment] 2023-07-18 22:27
Duplicate of https://github.com/microsoft/vscode-docs/issues/6496

**Closed by rzhao271** 2023-07-18 22:27 UTC
