### ISSUE TITLE
404 in download page

### ISSUE THREAD

**Issue by napsta32** [microsoft/vscode-docs#6496] opened 2023-07-18 15:36 UTC
I was downloading vscode for macOS here: https://code.visualstudio.com/download
However sometimes it automatically redirects me to: https://code.visualstudio.com/sha/undefined
I am not sure what is going on or if has anything to do with this repo. I was unable to download vscode for a while.

![image](https://github.com/microsoft/vscode-docs/assets/26403251/97bba546-5a3a-4cbf-8946-55767dc67388)

**Comment by Margery0011** [comment] 2023-07-18 16:48
Same

**Comment by jamanjeval** [comment] 2023-07-18 17:09
same

**Comment by iqra-khan0635** [comment] 2023-07-18 17:42
same

**Comment by SergioEnrique** [comment] 2023-07-18 19:06
same vscode and insiders

**Comment by markuskiller** [comment] 2023-07-18 19:27
same here and still ongoing

**Comment by 11aghayan** [comment] 2023-07-18 19:35
same

**Comment by mmelgarejogit** [comment] 2023-07-18 19:37
same(windows)

**Comment by tealingg** [comment] 2023-07-18 19:49
same here for macos. anyone got a download link?

**Comment by Approx104** [comment] 2023-07-18 20:04
Direct download link for .deb (x64)?

**Comment by mazcom** [comment] 2023-07-18 20:16
same

**Comment by louisleger** [comment] 2023-07-18 20:29
same

**Comment by Mathpants** [comment] 2023-07-18 20:33
MS Store download seems to be working for those looking for a download link.

**Comment by gregvanl** [comment] 2023-07-18 21:35
You can create the download URL by following the platform-specific URL patterns documented in https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

For example: https://update.code.visualstudio.com/1.80.1/win32-x64/stable

**Comment by rzhao271** [comment] 2023-07-18 22:37
We've found a root cause and are rolling out the fix to the instances.

**Comment by Kaally** [comment] 2023-07-18 23:22
> Direct download link for .deb (x64)?

download via windows app store for now

**Comment by rzhao271** [comment] 2023-07-18 23:51
The issue should be fixed now. I'll run a last set of checks and then close this issue.
If the problem persists, try clearing your browser cache.
If it still persists, don't hesitate to comment on this issue.

**Closed** 2023-07-18 23:54 UTC
Labels: important, install-update, vscode-website, docs-experience

**Comment by Kaally** [comment] 2023-07-19 00:08
Hi I hope you're doing well. I just wanted to drop you a quick note to say
thank you for addressing the issue promptly.

I'm happy to confirm that the problem has been resolved now. I really
appreciate your efforts in getting this fixed.

If any similar issues arise in the future, I won't hesitate to let you
know. Once again, thank you for your support!

Best regards,
 Kaally
 GitHub username: Kaally


Em ter., 18 de jul. de 2023 7:54 PM, Raymond Zhao ***@***.***>
escreveu:

**Comment by Yen-Lung-Huang** [comment] 2023-11-25 04:10
I can't access the VSCode website https://code.visualstudio.com/ on my Windows 11 laptop for 2 months. However, I installed VSCode when it was still accessible half a year ago and have been using it normally until now, but I still don’t understand why I can’t access it now? My mobile phone can access the VSCode website normally under the same Wi-Fi domain.
![Snipaste_2023-11-25_12-05-16](https://github.com/microsoft/vscode-docs/assets/73886748/a7a9ddb4-119d-4aa6-9a98-a2c489f2690c)
