### ISSUE TITLE
This page is using the development build of React.

### ISSUE THREAD

**Issue by cheesemacfly** [Microsoft/vscode-docs#978] opened 2017-05-03 15:24 UTC
Not sure if this is the best place to report this issue but it appears that the documentation section (and even the whole code.visualstudio.com website) is running the dev version of react on production.

The react chrome plugin shows the following message when browsing the website:

> This page is using the development build of React. 🚧
> 
> Note that the development build is not suitable for production. 
> Make sure to use the production build before deployment.

Here's the guide to build the app for production in case it's needed: https://facebook.github.io/react/docs/optimizing-performance.html#use-the-production-build

**Comment by gregvanl** [comment] 2017-05-03 18:05
Hi @cheesemacfly, this is a duplicate of https://github.com/Microsoft/vscode-docs/issues/960 which was ported to our website repo. Thank you for taking the time to report the issue.

**Closed by gregvanl** 2017-05-03 18:05 UTC
