### ISSUE TITLE
Errors & Warnings: moved to its own panel

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#408] opened 2016-07-04 12:57 UTC
Refs: https://code.visualstudio.com/docs/editor/editingevolved#_errors-warnings

This section should be updated with the new "Problems" panel introduced in the May milestone.

**Comment by gregvanl** [comment] 2016-07-05 18:06
Duplicate of https://github.com/Microsoft/vscode-docs/issues/389

**Closed by gregvanl** 2016-07-05 18:06 UTC
