### ISSUE TITLE
macOS Catalina 打不开 vscode

### ISSUE THREAD

**Issue by GenesisLQ** [microsoft/vscode-docs#3152] opened 2019-10-12 02:29 UTC

**Comment by gregvanl** [comment] 2019-10-12 17:23
Previous text translated to "Download vscode today and prompt "Can't open because Apple can't check if it contains malware""

I believe this is a duplicate of https://github.com/microsoft/vscode/issues/82424

**Closed by gregvanl** 2019-10-12 17:23 UTC
