### ISSUE TITLE
docs/extensionAPI/vscode-api#_extensions has a misformed code block

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode-docs#88] opened 2015-12-20 11:54 UTC
The underlying markdown HTML is visible rather than the intended code-block output as shown below.

![image](https://cloud.githubusercontent.com/assets/2957173/11917835/1349379e-a721-11e5-8e0a-c395ea79abd1.png)

**Comment by jrieken** [comment] 2015-12-21 08:46
That is in the tooling which makes razor. the generated markdown is still proper

**Comment by gregvanl** [comment] 2015-12-28 21:58
Duplicate of #83

**Closed by gregvanl** 2015-12-28 21:58 UTC
Labels: bug
