### ISSUE TITLE
Task Runner: Define array of tasks

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#250] opened 2016-03-29 16:30 UTC
_From @pcgeek86 on March 29, 2016 16:24_

- VSCode Version: 0.10.11
- OS Version: Mac OS X El Capitan

The documentation for Task Runners doesn't indicate how to define more than one task in the `tasks.json` file. How do I define more than one? The default `tasks.json` file that gets auto-generated only has one task definition. I tried creating a JSON array, but received error messages about the file format.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

_Copied from original issue: Microsoft/vscode#4757_

**Comment by gregvanl** [comment] 2016-03-30 01:06
Duplicate of https://github.com/Microsoft/vscode-docs/issues/248

**Closed by gregvanl** 2016-03-30 01:06 UTC
