### ISSUE TITLE
Python Matplotlib Unable to Install

### ISSUE THREAD

**Issue by Aguared** [Microsoft/vscode-docs#1776] opened 2018-08-08 22:13 UTC
Whenever I type 'pip install matplotlib' into the command terminal the following error is given:

The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

**Comment by gregvanl** [comment] 2018-08-09 14:56
Looks like duplicate of https://github.com/Microsoft/vscode-docs/issues/1774

**Closed by gregvanl** 2018-08-09 14:56 UTC
