### ISSUE TITLE
Extensions Management: update for new extensions viewlet

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#405] opened 2016-07-04 12:53 UTC
Refs: https://code.visualstudio.com/docs/editor/extension-gallery

We no longer have a quick open management for extensions, but rather a viewlet. As such the extensions management topic should be updated to accomodate for that.

**Comment by gregvanl** [comment] 2016-07-05 18:17
Duplicate of https://github.com/Microsoft/vscode-docs/issues/400

**Closed by gregvanl** 2016-07-05 18:17 UTC
