### ISSUE TITLE
Documentation for Keybinding Customisation should list `when' predicates

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-docs#249] opened 2016-03-28 19:58 UTC
_From @stephenmartindale on March 27, 2016 17:5_

- VSCode Version: 0.10.11
- OS Version: Microsoft Windows 10

Steps to Reproduce:

1. Visit the documentation at https://code.visualstudio.com/docs/customization/keybindings
2. Observe the truly excellent coverage of 'key' and 'command' and other concepts, particularly the "Accepted Keys" and "Keyboard layouts" subheadings.
3. Observe that there is no table of predicates that may be used for `when' attributes - there is not even a note about the use of logical operators.

Inside VS Code, when the default keyboard shortcut definitions are open, you can discover a few of the predicates by reading existing definitions. For example, without scrolling down, I can see that `editorTextFocus`, `inReferenceSearchEditor` and `editorHasSelection` all exist and that they can be combined with the `&&` operator. The only one that is mentioned in the documentation is `editorTextFocus`.

_Copied from original issue: Microsoft/vscode#4697_

**Comment by gregvanl** [comment] 2016-03-29 17:23
Closing as a duplicate of https://github.com/Microsoft/vscode-docs/issues/124

**Closed by gregvanl** 2016-03-29 17:23 UTC
