### ISSUE TITLE
 404 error

### ISSUE THREAD

**Issue by Amin-Keshavarz** [microsoft/vscode-docs#6508] opened 2023-07-18 21:11 UTC
When trying to download VS Code, we encounter a 404 error. What is the solution?

**Comment by muhohokenya** [comment] 2023-07-18 21:22
Same issue

**Comment by TomQuixote** [comment] 2023-07-18 21:24
Same here

**Comment by rajanazirul** [comment] 2023-07-18 21:27
same here

**Comment by gregvanl** [comment] 2023-07-18 21:37
As a workaround, you can create the download URL by following the platform-specific URL patterns documented in https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

For example: https://update.code.visualstudio.com/1.80.1/win32-x64/stable

**Comment by rzhao271** [comment] 2023-07-18 22:27
Duplicate of https://github.com/microsoft/vscode-docs/issues/6496

**Closed by rzhao271** 2023-07-18 22:27 UTC
