### ISSUE TITLE
Heading “Thanks for downloading VS Code for…” renders link to version number unclickable.

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode-docs#4683] opened 2021-07-16 01:35 UTC
https://user-images.githubusercontent.com/8168391/125878150-15002c12-ac25-4d2b-b3c5-45c045f3122b.mp4

When inspecting element on what appears to be the version number, the heading is revealed in the Elements panel instead.

![image](https://user-images.githubusercontent.com/8168391/125878273-a5d29c3c-7773-47ca-9f6c-cccd7ab93b6a.png)

**Comment by gregvanl** [comment] 2021-07-22 17:52
Hi @infinnie Thank you for pointing this out and creating an issue. I'm closing the issue since we're unlikely to fix it as the work around is to select the "Updates" link in the top navigation bar, which will also take the user to the latest release notes.
The issue is due to how we support the always visible top navigation bar (it doesn't scroll off the top of the screen).

**Comment by infinnie** [comment] 2021-07-26 03:40
What about using a larger z-index for the banner containing the version number?

**Comment by gregvanl** [comment] 2021-07-26 14:05
Hi @infinnie That does work! Thanks for the fix. Will update the website shortly.

**Closed** 2021-07-26 18:55 UTC
Labels: docs-experience
