### ISSUE TITLE
Most Popular Extensions should mention 'Show popular' action in extensions viewlet

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#398] opened 2016-07-04 12:33 UTC
Ref: https://code.visualstudio.com/docs#top-extensions

Should mention that we now have an action to show the most popular extension via the extension viewlet.

**Comment by gregvanl** [comment] 2016-07-14 22:19
Assigning to Brad and Wade since this is a suggestion for the /docs page which isn't in vscode-docs.

**Comment by gregvanl** [comment] 2016-07-18 21:26
Website content

**Comment by waderyan** [comment] 2016-07-21 19:35
The feedback is great here. I decided to put a link to the extension gallery page which goes into detail about finding extensions in product. I didn't want to reproduce the content on the docs index page as it would make the page more crowded than it needed to be.

**Closed by waderyan** 2016-07-21 19:35 UTC
