### ISSUE TITLE
Break "Node Debugging" out onto its own page

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-docs#712] opened 2016-12-12 19:18 UTC
I think there's a lot more that could be said about node debugging, especially troubleshooting. Since the "Node debugging" section is already almost half the debugging page, I think it might deserve its own page, beyond being a section of the general debugging page.

**Comment by gregvanl** [comment] 2016-12-12 19:29
Duplicate of https://github.com/Microsoft/vscode-docs/issues/448. Andre agrees.

**Closed by gregvanl** 2016-12-12 19:29 UTC
Labels: debug
