### ISSUE TITLE
Unable to use "Python: Select Interpreter" to select a conda environment, the conda environment is not shown in the drop down list

### ISSUE THREAD

**Issue by MattGurney** [microsoft/vscode-docs#4088] opened 2020-10-28 14:41 UTC
I created a new conda environment using:
`conda create -n test1 python=3.8 `
The environment is created successfully

I activate the environment using:
`conda activate test1`

The prompt changes to indicate the environment is activated.

I close all VSC windows.

I open VSC to a python project.

In VSC I activate "Python: Select Interpreter"

The new environment is not shown in the list, other environments are shown such as:

- default Mac python
- anaconda base 
- ~./pyenv/shims/python
- etc

I can wait multiple minutes, the new environment never appears.

I also tried:
1. in mac terminal activate the desired environment
2. in mac terminal cd to python project folder
3. in mac terminal run
`code .`
4. This opens VSC for the python project, but again the conda environment is not selected and not in the list of drop down python interpreters.

I am using: 
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (2 wks ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

conda --version
conda 4.8.3

uname -a
Darwin my-mac.lan 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

**Comment by gregvanl** [comment] 2020-10-28 16:13
Possible duplicate of https://github.com/microsoft/vscode-docs/issues/4072

**Comment by gregvanl** [comment] 2020-10-28 16:20
@JoshuaPartlow This seems to be a very common user friction point (~40 closed vscode-docs issues related to selecting the Python interpreter). Can we add more instructions or perhaps a troubleshooting section?

**Comment by JoshuaPartlow** [comment] 2020-10-28 17:19
@luabud for awareness. 

Hi @MattGurney - Thanks for opening an issue. Have you tried manually setting the interpreter path (first option in the interpreter drop down) or tried setting the "python.venvFolders": [] setting (**Python: Venv Folders** in User Settings for the Python extension) ? Also, could you confirm which version of the Python extension you're using, I didn't see it in the information above.

**Comment by JoshuaPartlow** [comment] 2020-11-03 17:21
Closing due to time passed. If this is still an issue, please feel free to reopen.

**Closed by JoshuaPartlow** 2020-11-03 17:21 UTC
Labels: python, support-request
