### ISSUE TITLE
Version Control Documentation needs to be updated

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#964] opened 2017-04-30 11:21 UTC
https://code.visualstudio.com/docs/editor/versioncontrol

This section is now out of date and needs to be updated to the latest. Should also mention the different SCM providers that are  now available on the marketplace.

**Comment by gregvanl** [comment] 2017-04-30 22:27
Duplicate of https://github.com/Microsoft/vscode-docs/issues/959

**Closed by gregvanl** 2017-04-30 22:27 UTC
