### ISSUE TITLE
STOP CLOSING THREADS DOWNLOAD WONT WORK

### ISSUE THREAD

**Issue by megatronskneecap** [microsoft/vscode-docs#6503] opened 2023-07-18 19:22 UTC

**Comment by gregvanl** [comment] 2023-07-18 19:28
There is already a vscode-docs issue tracking the download issue and it is being worked on by VS Code engineering.

Duplicate of https://github.com/microsoft/vscode-docs/issues/6496

**Closed by gregvanl** 2023-07-18 19:28 UTC
Labels: duplicate

**Comment by megatronskneecap** [comment] 2023-07-18 19:32
> There is already a vscode-docs issue tracking the download issue and it is being worked on by VS Code engineering.
> 
> Duplicate of #6496

Yeah but bro it won't work I'm not sure why you're marking them as duplicates and fixed
