### ISSUE TITLE
Can Code be more "Copy & Run"?

### ISSUE THREAD

**Issue by dead-lee** [Microsoft/vscode-docs#874] opened 2017-03-07 02:29 UTC
I'm working for a bank.  I don't have admin right to my desktop. 
I copy the zip version of Code, and unzip it to "My documents" folder, which is the only place I have write access.
Try to run code but it cannot show up after 10 minutes. I can find it running in background, so I must kill it.
I think it may try to setup environment variants, which is not allowed. Or trying to access internet, which is not allowed either.
So I hope Code can show up any way, as I can use it to read existing codes. 
I also hope all extensions can be installed via offline mode. Since only IE is allowed to access internet, all the others are blocked.

**Comment by Tyriar** [comment] 2017-03-11 00:34
This is a duplicate of https://github.com/Microsoft/vscode/issues/329 which asks for a portable version of VS Code. Right now the best you can do is downloading the zip and running:

```
<extracted location>/bin/code` --user-data-dir <some path> --extensions-dir <some other path>
```

With this the 2 primary folders that VS Code needs to operate will be where you specify in the command line arguments. VS Code will still attempt to access the internet, there's no way to stop this currently. You can read https://github.com/Microsoft/vscode/issues/329 for more details on the future plans.

**Closed by Tyriar** 2017-03-11 00:34 UTC

**Comment by bernardoadc** [comment] 2021-01-14 18:50
My 2 cents adition from a very similar scenario: you can still use `set` to set environment variables, valid only for active session. You can create a batch file that will set variables and then run VSCode properly (my includes portable git, node, etc).
