### ISSUE TITLE
Carousel Prevents People With Disabilities From Reading Front Page Effectively

### ISSUE THREAD

**Issue by jhomme** [microsoft/vscode-docs#3956] opened 2020-08-21 18:29 UTC
Hi,
The carousel on the front page of the docs cannot bestopped, started, or paused via keyboard. This prevents screen reader users and people with motor disabilities from reading the page properly.

**Comment by gregvanl** [comment] 2020-11-10 05:24
Duplicate of https://github.com/microsoft/vscode-docs/issues/3715 fixed July 2020

**Closed by gregvanl** 2020-11-10 05:24 UTC
Labels: accessibility, doc-experience, vscode-website
