### ISSUE TITLE
Review common question sections

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-docs#376] opened 2016-07-04 10:59 UTC
I am not sure about the common question section in each document. I think it is too much repetition (it states something that is already present in the document). And if it states something new, why isn't it part of the document itself. I think it makes only sense to have one common question document which then points back to the normal documentation for 'fast' readers.

**Comment by gregvanl** [comment] 2016-07-18 21:27
Duplicate of https://github.com/Microsoft/vscode-docs/issues/439

**Closed by gregvanl** 2016-07-18 21:27 UTC
Labels: triage
