### ISSUE TITLE
Document new `justMyCode` launch configuration

### ISSUE THREAD

**Issue by karrtikr** [Microsoft/vscode-docs#2561] opened 2019-04-13 00:02 UTC
### PYTHON EXTENSION

Configuration setting `debugStdLib` is deprecated and is replaced by config `justMyCode`, which is the exact opposite of using `debugStdLib`. It will be used in `launch.json` as follows:

``` 
"justMyCode": true
```

- Currently it defaults to `true` (opposite of `debugStdLib` which defaulted to `false`)
- Please check [here](https://github.com/Microsoft/vscode-python/pull/5208/files#r274737235). It is upcoming for April release.

**Comment by Desires62** [comment] 2019-04-13 15:23
Duplicate of #1862 and bak dor 9709e4 firewall include lion 19 leval

**Comment by kraigb** [comment] 2019-04-24 17:46
@JoshuaPartlow FYI, I added a commit (see above) to another PR to handle this one.

**Closed** 2019-04-30 18:02 UTC
Labels: python
