### ISSUE TITLE
Unable to download.. throws 404 error

### ISSUE THREAD

**Issue by reventhk** [microsoft/vscode-docs#6501] opened 2023-07-18 19:02 UTC
While downloading visual studio editor it is throwing 404 error.  

![image](https://github.com/microsoft/vscode-docs/assets/4659872/e769520c-6ea5-407d-b82e-bf048a26727c)

**Comment by gregvanl** [comment] 2023-07-18 19:09
Duplicate of https://github.com/microsoft/vscode-docs/issues/6496

**Closed by gregvanl** 2023-07-18 19:09 UTC
Labels: duplicate
