### ISSUE TITLE
Missing " in args description of c++ launch-json-reference.md

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#3098] opened 2019-09-19 11:07 UTC
There is a `"` character missing in the args description of `docs/cpp/launch-json-reference.md`
```
For example, ["{\\\"arg1\\\": true}] will send {"arg1": true} to your application.
```
should be
```
For example, ["{\\\"arg1\\\": true}"] will send {"arg1": true} to your application.
```

Is this specific to C++ debugging or should it also be mentioned in `docs/editor/debugging.md`?

**Comment by gregvanl** [comment] 2019-09-19 16:41
Thanks for entering an issue.
Duplicate of https://github.com/microsoft/vscode-docs/issues/3071
Fixed with https://github.com/microsoft/vscode-docs/commit/7ff429c2a813f492eb9d0881e6da1a1c4260bf36
Will check into whether this is needed in general for launch.json arguments.

**Closed by gregvanl** 2019-09-19 16:41 UTC
