### ISSUE TITLE
No way to see keybindings from an android browser

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docs#483] opened 2016-07-29 14:19 UTC
Inside an android browser the keybindings for other platforms should be shown in parenthesis, same as it is done for Safari on the iPhone.

![image](https://cloud.githubusercontent.com/assets/172399/17251250/286fb6bc-55a8-11e6-9920-baa47e63f68c.png)

**Comment by gregvanl** [comment] 2017-01-10 19:19
Duplicate of https://github.com/Microsoft/vscode-website/issues/430. We should show key bindings for all available platforms.

**Closed by gregvanl** 2017-01-10 19:19 UTC
