### ISSUE TITLE
ModuleNotFoundError: No module named 'keras'

### ISSUE THREAD

**Issue by shenlong2010** [microsoft/vscode-docs#4182] opened 2020-12-15 17:51 UTC
Hi,

This is my first time posting an issue, please let me know if I do it wrong or anything.

I am currently following the instructions in Data Science in Visual Studio Code.
Got the error until "(Optional) Use a neural network to increase accuracy":

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-92-03cd5e6c4740> in <module>
----> 1 from keras.models import Sequential
      2 from keras.layers import Dense
      3 
      4 model = Sequential()

ModuleNotFoundError: No module named 'keras'

Note: I ran "conda create -n myenv python=3.7 pandas jupyter seaborn scikit-learn keras tensorflow"
and changed my "Python: Select Interpreter" accordingly

**Comment by shenlong2010** [comment] 2020-12-15 18:23
I tried to run Keras directly on Jupyter Notebook and it worked.

**Comment by JoshuaPartlow** [comment] 2020-12-15 19:25
hi @shenlong2010 - just to confirm, could you run `conda list -n myenv` and verify the keras package is shown? When you did get Keras to work, were you using the myenv environment or the base conda environment?

**Comment by shenlong2010** [comment] 2020-12-16 02:26
Keras package is shown after I ran the command
...
keras                     2.4.3                         0
keras-applications        1.0.8                      py_1
keras-base                2.4.3                      py_0
keras-preprocessing       1.1.0                      py_1
...

And yes, I'm in myenv environment, not the base conda env.
------
Note: I tried "import Keras" package individually, it still showed the error. Other works fine, it only has problems with Keras.

**Comment by JoshuaPartlow** [comment] 2020-12-16 21:21
@jmew / @claudiaregio - Would either of you be able to help with what might be going on here?

**Comment by claudiaregio** [comment] 2020-12-16 21:25
Hi @shenlong2010, can you please provide the following information: 

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

Can you also screen record what you are seeing using https://www.screentogif.com/   
(Please make sure to include the entire screen so we do not miss any potential helpful information)

**Comment by shenlong2010** [comment] 2020-12-16 21:51
Hi @claudiaregio, follow up with the information
- VS Code version: 1.52.0
Version: 1.52.0 (user setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

- Jupyter Extension version
![jupyter version](https://user-images.githubusercontent.com/57968871/102410352-7093c280-3fbe-11eb-8df5-a2396fc3ca79.PNG)

- Python 3.7.9 64-bit

- Microsoft Windows 10.0.19041.630

- Python and Anaconda version:
![Python env](https://user-images.githubusercontent.com/57968871/102408534-b8fdb100-3fbb-11eb-9b8c-754149e60760.PNG)

- Virtual env: I followed the instruction on Microsoft website so it should be this env
conda create -n myenv python=3.7 pandas jupyter seaborn scikit-learn keras tensorflow

- Jupyter server: local

**Comment by claudiaregio** [comment] 2020-12-16 23:22
@shenlong2010 The extension version refers to the Jupyter Extension and Python Extension within VS Code. It is found in the extensions tab. (The gray number next to the name is the extension version) 

![image](https://user-images.githubusercontent.com/19276747/102418161-0b39d480-3fb2-11eb-81d1-26c9df9be771.png)

I'm still having trouble understanding if you are using a Jupyter notebook or a Python script. 

Could you please recreate the issue you are experiencing and record using -> https://www.screentogif.com/
The Python interpreter in the bottom left is necessary for the setup when using Python scripts but the kernel picker in the top right is necessary for Jupyter notebooks. Based on your feedback I am still having trouble understanding what you are using. It would be very beneficial if you could record yourself running into the issue, that way we can help debug further.

**Comment by shenlong2010** [comment] 2020-12-16 23:39
Sorry I still a newbie at this.

Jupyter v2020.12.414227025

![Uploading ModuleError.gif…]()

**Comment by claudiaregio** [comment] 2020-12-16 23:43
No problem we are working through it :) 

It looks like the gif didn't finish uploading before you posted, could you try again? you can click the "preview" tab on the github message to double check that it loaded properly.  

![image](https://user-images.githubusercontent.com/19276747/102419806-6f11cc80-3fb5-11eb-9e5a-4e51270c3743.png)

**Comment by shenlong2010** [comment] 2020-12-16 23:45
![ModuleError](https://user-images.githubusercontent.com/57968871/102419871-be182b80-3fce-11eb-9bc3-6279901c4f8e.gif)

Also: the code was referenced from https://code.visualstudio.com/docs/python/data-science-tutorial

**Comment by claudiaregio** [comment] 2020-12-16 23:49
ok great, can you click in the top right where it says "Python 3: Idle". A drop down menu will show up in the top center of the page. You should see a list of available kernels. Can you show us a screenshot of the options that are available on drop down?

**Comment by shenlong2010** [comment] 2020-12-16 23:54
![Capture](https://user-images.githubusercontent.com/57968871/102420455-2e737c80-3fd0-11eb-9a3e-37290ad374b0.PNG)

**Comment by claudiaregio** [comment] 2020-12-16 23:56
Can you select the 3rd option, the one that ends in ('myenv':conda) and see if the issue still persists?

**Comment by shenlong2010** [comment] 2020-12-16 23:58
![ModuleError2](https://user-images.githubusercontent.com/57968871/102420693-b2c5ff80-3fd0-11eb-9ffa-c8551bf7654f.gif)

**Comment by claudiaregio** [comment] 2020-12-17 00:11
I was not able to reproduce this issue earlier. 

![image](https://user-images.githubusercontent.com/19276747/102421280-ef85fc80-3fb8-11eb-9f14-6032186a768f.png)

What command did you use to install keras onto your conda environment?

**Comment by shenlong2010** [comment] 2020-12-17 00:13
conda create -n myenv python=3.7 pandas jupyter seaborn scikit-learn keras tensorflow

**Comment by claudiaregio** [comment] 2020-12-17 00:13
Please try conda install -c conda-forge keras in your conda terminal

**Comment by shenlong2010** [comment] 2020-12-17 00:19
Ok, after running conda install -c conda-forge keras, it updated the package. It's working now.

**Comment by claudiaregio** [comment] 2020-12-17 00:26
Great! Glad to hear it wasn't a vs code issue :) 
Closing as this was an environment installation problem

**Closed** 2020-12-17 06:08 UTC
Labels: python, support-request
