### ISSUE TITLE
Docker: Build Image results in an error

### ISSUE THREAD

**Issue by jainr** [microsoft/vscode-docs#2700] opened 2019-05-24 18:40 UTC
Richins-MBP:python-sample-vscode-flask-tutorial $ docker build --rm -f "Dockerfile" -t python-sample-vscode-flask-tutorial:latest .
Sending build context to Docker daemon  22.53kB
Step 1/7 : FROM tiangolo/uwsgi-nginx-flask:python3.6
Get https://registry-1.docker.io/v2/tiangolo/uwsgi-nginx-flask/manifests/python3.6: unauthorized: incorrect username or password

Not sure if I am doing anything incorrectly, and I don't believe I need dockerhub login to get this to work but I did it anyways.

**Comment by gregvanl** [comment] 2019-05-24 20:01
Hi @jainr Is this issue related to a particular VS Code python tutorial? Can you clarify which step in the tutorial is causing the issue? Thanks

**Comment by jainr** [comment] 2019-05-28 16:58
Hi @gregvanl - Can't get docker build to run from vscode, this is the step. The command runs fine on command line.

Build and test the image
With the necessary Dockerfile in place, you're ready to build the Docker image and run it locally:

Make sure that Docker is running on your computer.

**On the VS Code Command Palette (⇧⌘P), select Docker: Build Image.**

When prompted for the Docker file, choose the Dockerfile that you created in the previous section. (VS Code remembers your selection so you won't need to enter it again to rebuild.)

When prompted for a name to give the image, use a name that follows the conventional form of <registry or username>/<image name>:<tag>, where <tag> is typically latest. Here are some examples:

**Comment by gregvanl** [comment] 2019-05-28 17:37
https://code.visualstudio.com/docs/python/tutorial-deploy-containers#_build-and-test-the-image

**Comment by jainr** [comment] 2019-05-28 19:26
Sorry should have made that clear earlier

**Comment by kraigb** [comment] 2019-06-03 16:33
Assigning to myself; @jainr I'll be taking a look at this shortly, as I'll be reviewing the content hopefully this week in preparation for migrating it to the Azure documentation.

**Comment by kraigb** [comment] 2019-06-05 23:34
@jainr I tried all this again but couldn't reproduce the error. It's strange that it runs on the CLI just fine, but not in VS Code. Have you tried it again in VS Code? A little searching suggests that there could be intermittent auth errors like this, and in any case you shouldn't need credential to access that base image anyway. 

In the end, I don't think it's anything to do with VS Code, but with docker build itself, because VS Code is simply invoking that command in the terminal. But with that in mind, have you perhaps used docker login from the VS Code terminal before using the build command?

**Closed** 2019-06-10 03:03 UTC
Labels: python
