### ISSUE TITLE
Keybinding list needs updating

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#443] opened 2016-07-04 14:10 UTC
refs: https://code.visualstudio.com/docs/customization/keybindings

We have introduced some new actions in the last couple of releases and the list of keybindings needs an update.

**Comment by gregvanl** [comment] 2016-07-05 18:33
Duplicate of https://github.com/Microsoft/vscode-docs/issues/422

**Closed by gregvanl** 2016-07-05 18:33 UTC
