### ISSUE TITLE
VSCode installer out of order

### ISSUE THREAD

**Issue by dib4399** [microsoft/vscode-docs#6502] opened 2023-07-18 19:03 UTC
The link doesn't work to download VS. All I see is a purple 404 error screen.

**Comment by Imagine96** [comment] 2023-07-18 19:05
same

**Comment by SergioEnrique** [comment] 2023-07-18 19:05
same.
vscode and vscode insiders aren't working

**Comment by gregvanl** [comment] 2023-07-18 19:10
Duplicate of https://github.com/microsoft/vscode-docs/issues/6496

**Closed by gregvanl** 2023-07-18 19:10 UTC
Labels: duplicate
