### ISSUE TITLE
Editing and Navigating C++ CodeDuplicate information in 

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-docs#7278] opened 2024-05-12 14:41 UTC
https://github.com/microsoft/vscode-docs/blob/a9c9c282a44f2197b35d983ecb8d2d6f438de69c/docs/cpp/cpp-ide.md?plain=1#L22-L28

**Comment by ntrogh** [comment] 2024-05-13 07:48
Duplicate of #7279 
Fixed in #7281

**Closed by ntrogh** 2024-05-13 07:48 UTC
Labels: doc-bug
