### ISSUE TITLE
Formatting issues with the devcontainer.json reference section

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-docs#3470] opened 2020-03-12 16:23 UTC
Currently there are some long strings in the devcontainer.json reference out of necessity.  These seem to be causing formatting problems with the right nav bar.  See red box in image below.

![image](https://user-images.githubusercontent.com/312252/76542747-af4e8800-6442-11ea-92d2-016dca57f321.png)

This occurs on macOS version of Edge Dev.

![image](https://user-images.githubusercontent.com/312252/76542830-cee5b080-6442-11ea-8aeb-1b5122534339.png)

On Chrome and Safari, I don't see the right nav staying when scrolling, so you don't see it, however you can see the table is sticking out, so presumably the underlying CSS issue happens there too.

![image](https://user-images.githubusercontent.com/312252/76543005-1d934a80-6443-11ea-86f6-b4f88c511aa0.png)

//cc: @gregvanl

**Comment by gregvanl** [comment] 2020-03-19 19:55
Duplicate of https://github.com/microsoft/vscode-docs/issues/3321

**Closed by gregvanl** 2020-03-19 19:55 UTC
Labels: doc-experience
