### ISSUE TITLE
I literally can't download anything... Just gives a 404

### ISSUE THREAD

**Issue by megatronskneecap** [microsoft/vscode-docs#6500] opened 2023-07-18 18:55 UTC
I'm only trying to download the .dmg version for Mac but at the moment the downloads page just gives a 404...

**Comment by gregvanl** [comment] 2023-07-18 19:09
Duplicate of https://github.com/microsoft/vscode-docs/issues/6496

**Closed by gregvanl** 2023-07-18 19:09 UTC
Labels: duplicate
