### ISSUE TITLE
feat request: add others languages

### ISSUE THREAD

**Issue by r3nanp** [microsoft/vscode-docs#4228] opened 2021-01-08 22:39 UTC
### Add others languages

**It would make easier to learn how to use Visual Studio Code!**

**Comment by gregvanl** [comment] 2021-01-08 22:46
Hi @r3nanp Thank you for submtting an issue and your interest in the VS Code documentation.
I think you are asking for the website to be translated into other languages. If so, this is a duplicate of https://github.com/microsoft/vscode-docs/issues/3260.
At present, we don't have plans to support non-English versions of code.visualstudio.com but this may change in the future

**Closed by gregvanl** 2021-01-08 22:46 UTC
