### ISSUE TITLE
Can we have c++ demo project using VStudio also with clang-cl.exe ?

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/vscode-docs#4167] opened 2020-12-08 18:30 UTC
https://github.com/microsoft/vscode-remote-try-cpp/issues/10#issue-759671095

**Comment by gregvanl** [comment] 2020-12-16 05:20
Closing as duplicate of https://github.com/microsoft/vscode-docs/issues/4168, which covers adding documentation.

**Closed by gregvanl** 2020-12-16 05:20 UTC
Labels: C++, support-request
