### ISSUE TITLE
VSCode activity bar pictures should be updated to include extensions viewlet icon

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#395] opened 2016-07-04 12:30 UTC
I think the vscode pictures in the overview section and on other highly visible places should be updated to include the extensions viewlet in the activity bar

![screen shot 2016-07-04 at 14 29 29](https://cloud.githubusercontent.com/assets/1926584/16560436/bd0ea97c-41f3-11e6-93cb-1dacde6b2e82.png)

**Comment by gregvanl** [comment] 2016-07-05 17:23
Duplicate of https://github.com/Microsoft/vscode-docs/issues/385

**Closed by gregvanl** 2016-07-05 17:23 UTC
