### ISSUE TITLE
code written in video is wrong

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-docs#1201] opened 2017-10-10 15:30 UTC
https://code.visualstudio.com/docs/editor/userdefinedsnippets shows a video in which the snippet isn't filled in properly. `GET` is a method, `/users` is an url
 
<img width="445" alt="screen shot 2017-10-10 at 17 30 23" src="https://user-images.githubusercontent.com/1794099/31395294-c0f439bc-ade0-11e7-9586-8aa9ee2fe7a6.png">

**Comment by gregvanl** [comment] 2017-10-10 16:42
Duplicate of https://github.com/Microsoft/vscode-docs/issues/1100

**Closed by gregvanl** 2017-10-10 16:42 UTC
Labels: bug, duplicate
