### ISSUE TITLE
Download vs code extensions via Commandline/API

### ISSUE THREAD

**Issue by amey2688** [microsoft/vscode-docs#5619] opened 2022-09-07 14:17 UTC
We have a requirement in our organization where we need to restrict user access to public marketplace place  and maintain extension in a centralised repository . in order to implement restricted access and maintain vs code extensions,we need to keep latest extensions in our private repository

Is there any way we can download a a particular extension  from marketplace via and API or commandline so the process can be automated? or is there any other way to achieve sync of latest  vs code extensions via a private repository like jfrog artifactory?

**Comment by isidorn** [comment] 2022-09-09 09:43
Hi, thanks for opening this issue, however this is a duplicate of https://github.com/microsoft/vscode/issues/21839
This is currently not supported so I will close this as a duplicate.

On the other side, could you say what features are missing from the public marketplace so that you could use it in your organisation? What are your exact requirements? Thanks

**Closed by isidorn** 2022-09-09 09:43 UTC
Labels: support-request

**Comment by amey2688** [comment] 2024-01-09 09:50
Hi @isidorn is it possible to add a feature in market place to be able to download latest stable version of extension manually . normally when i click "download extension" link for any extension , it gives latest pre-release version wjocj is generally not recommended to use

**Comment by isidorn** [comment] 2024-01-09 11:42
@amey2688 currently not possible because Marketplace is not aware of pre-release versions.
This would be a request against a Marketplace and I suggest to file an issue here https://github.com/microsoft/vsmarketplace/
fyi @seaniyer

**Comment by seaniyer** [comment] 2024-01-10 22:02
FYI @JacquelineWiddis
