### ISSUE TITLE
License Agreement for MS Visual Studio Data Collection Opt out link is dead

### ISSUE THREAD

**Issue by cryptokitty22** [microsoft/vscode-docs#5092] opened 2022-01-13 03:19 UTC
Installation of Visual Studio Code (User) at License Agreement screen, section 2. DATA., link to how to disable telemetry reporting is conveniently unable to point to the proper place to opt out of data collection. I reside in the State of California with express provisions requiring an active opt out link
![001](https://user-images.githubusercontent.com/97650998/149259937-593fc7e8-e030-4a2c-a88a-24ac3a00e82d.JPG)
![002](https://user-images.githubusercontent.com/97650998/149259947-df61172a-e15a-4f45-a7a7-7fe266e7af33.JPG)
.

**Comment by gregvanl** [comment] 2022-01-13 06:18
Hi @cryptokitty22 Thanks for reporting this. This is a duplicate of https://github.com/microsoft/vscode/issues/139144, which is in the process of being fixed, and should be fixed in the next release.

**Closed by gregvanl** 2022-01-13 06:18 UTC

**Comment by gregvanl** [comment] 2022-01-18 19:19
This is fixed now on VS Code Insiders available at https://code.visualstudio.com/insiders/
