### ISSUE TITLE
Basic Layout needs updates for tabs

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#388] opened 2016-07-04 12:20 UTC
Refs: https://code.visualstudio.com/docs/editor/codebasics#_basic-layout

We should update screen shots and mention that tabs are enabled by default and how to disable tabs if needed.

**Comment by gregvanl** [comment] 2016-07-05 17:11
Duplicate of https://github.com/Microsoft/vscode-docs/issues/387

**Closed by gregvanl** 2016-07-05 17:11 UTC
