### ISSUE TITLE
Ubuntu : how to install vscode with admin privileges

### ISSUE THREAD

**Issue by YeaseonZhang** [Microsoft/vscode-docs#562] opened 2016-09-08 15:16 UTC
VS Code always hint me **Run VS Code with admin privieges so the changes can be applied** 

What can I do?

**Comment by gregvanl** [comment] 2016-09-09 20:51
Closing as a duplicate of https://github.com/Microsoft/vscode/issues/11739

**Closed by gregvanl** 2016-09-09 20:51 UTC
